# Generated by Django 3.2.9 on 2021-12-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('someapp', '0003_auto_20211203_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='somemodel',
            name='other1',
            field=models.ManyToManyField(related_name='others', to='someapp.SomeOtherModel'),
        ),
    ]
